name: Create PR

on:
  workflow_dispatch:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c fix/hoge_${{ env.CURRENT_DATETIME }}
          git push -u origin fix/hoge_${{ env.CURRENT_DATETIME }}

      - name: Add date
      - run: date >> date.txt

      - name: Add and commit
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -N date.txt
          git diff --name-only --exit-code
        continue-on-error: true
    
      - name: Commit files
      - run: |
          git add date.txt
          git commit -m "Update"

      - run: gh pr create --title "$(git log -1 --oneline --pretty=format:'%s')" --body ""
        env:
          GH_TOKEN: ${{ github.token }}